### PR TITLE
Add esp status led

### PR DESCRIPTION
**Pull request by fredcazaux**
Hello @gekkekoe ,
First, thanks a lot for this great work...
I had rbroker ecodan-ha-local since yet, but missed some functions you added.
But there is one thing I liked in rbroker solution, was the status LED on the ESP. I like to see that everything works correctly directly in the heatpump room.
I managed to find a way to add wifi connection status on that LED (see commit on base.yaml). It should be possible to implement the same whole thing (check both wifi and uart) with the uart: debug: after: timout: and make the LED off, blink or fixed on...

I'm really new to ESPHome (first use yesterday with this). So I'm not really confident on how to implement this ths right way. However I can try and submit if you wish.

I've modified the ecodan-esphome.yaml and the esp32.yaml, but just for my personal needs and to adapt it with my DOIT ESP32. But I don't know how to create a request avoiding some commits, or how to revert commits in a branch??? Almost newbie in github contributing too...

Thanks again !

### CODE REVIEW

**Comment by gekkekoe** [comment]
Hi Thnx for the first try :)
you should try to isolate it in a separate yaml than can be included if you would like the feature (similar to debug). The main `esphome-ecodan.yaml` is the default, so you should keep those changes to yourself.

**Comment by gekkekoe** [comment]
please remove/undo changes in
- base.yaml
- esp32.yaml

and only add
`
            ## enable if you want built-in LED to monitor Wifi status
            #confs/status_led.yaml,
`
in esphome-ecodan.yaml then it's fine.
when you build for your card, just select the correct yaml in your own esphome-ecodan.yaml

**Comment by fredcazaux** [comment]
OK this time should be the good one... Still find that a undo would be easier to revert commits... Did copy paste from your original files, so should be exactly the same !

**Comment by gekkekoe** [comment]
https://github.com/gekkekoe/esphome-ecodan-hp/pull/45/files

still has a diff.

`git reset origin/main conf/esp32.yaml`

push and check changed files

**Comment by fredcazaux** [comment]
OK. I installed Github desktop... It seems revert or reset cannot be done from website... So reverted esp32.yaml to yours. And checked that there is non unwanted difference. Please forgive me for all those trials !

**Pull request merged**
